### ISSUE TITLE
PDFSpeaker

### ISSUE THREAD

**Issue by codinexpo** [codinexpo/PyPrograms#1]
Make an assistant that can read your pdfs

**Comment by Mikhaylov-yv** [comment]
Hey. I am using [PyPDF2](https://github.com/mstamy2/PyPDF2) for this purpose.
What exactly do you need to read in PDF?

**Comment by codinexpo** [comment]
> Hey. I am using [PyPDF2](https://github.com/mstamy2/PyPDF2) for this purpose.
> What exactly do you need to read in PDF?

Go ahead with this :+1:
