### ISSUE TITLE
YouTube videos downloader

### ISSUE THREAD

**Issue by codinexpo** [codinexpo/PyPrograms#10]
Write some python script that can help me to download videos from YouTube.

Additional:
Work on GUI too.

**Comment by ShraddhaDevaiya** [comment]
Can you please assign this task to me ? @codinexpo

**Comment by ChiragBolakani** [comment]
Hey can you assign me this task please? I have worked with python before and I can surely help with this.

**Comment by suraj111999** [comment]
Can you please assign this issue to me?

**Comment by codinexpo** [comment]
As first come first serve I'm assigning this to @ShraddhaDevaiya

**Comment by ShraddhaDevaiya** [comment]
Thanks @codinexpo, started working for this. 
First TODO : create script youtube_downloader.py

**Comment by codinexpo** [comment]
> Thanks @codinexpo, started working for this.
> First TODO : create script youtube_downloader.py
 Finished?

**Comment by codinexpo** [comment]
> Thanks @codinexpo, started working for this.
> First TODO : create script youtube_downloader.py

What's the status @ShraddhaDevaiya ?

**Comment by ShraddhaDevaiya** [comment]
yeah, it is working. Will push it in 1-2 hour.

**Comment by ShraddhaDevaiya** [comment]
Hi, One more input is needed from your side, do we need to pass link from command line argument or it is static into code ?

**Comment by codinexpo** [comment]
> Hi, One more input is needed from your side, do we need to pass link from command line argument or it is static into code ?

Pass link
